baseURL = "https://khcomic.com/"
languageCode = "zh-tw"
title = "📚K.H. Comic"
theme = "not-much"

[params]
theme = "auto"
palette = "eink"
showThemeNotice = true
showPostsSummary = true
summaryLength = 10

[outputs]
home = ["HTML", "JSON"]

# Navigation
[menu]
  #[[menu.main]]
  #  identifier = "home"
  #  name = "home"
  #  title = "Home"
  #  url = "/"
  #  weight = 1

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "About"
    url = "/about"
    weight = 2
	
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts"
    weight = 3
  
  [[menu.main]]
    identifier = "tags"
    name = "tags"
    title = "tags"
    url = "/tags"
    weight = 4

  [[menu.main]]
    identifier = "threads"
    name = "threads"
    title = "Threads"
    url = "https://www.threads.com/@kh.is.not.happy"
    weight = 5
	
  [[menu.main]]
    identifier = "threads_old"
    name = "legacy"
    title = "Threads"
    url = "https://www.threads.com/@kh.blcomic"
    weight = 6
	
  [[menu.main]]
    identifier = "search"
    name = "search"
    title = "Search"
    url = "/search"
    weight = 7

  [[menu.main]]
    identifier = "contact"
    name = "contact"
    title = "Threads"
    url = "mailto:kh.bl.comic@gmail.com"
    weight = 8